data = input()
new_data = data.replace('a', '')
new_data1 = new_data.replace('u', '')
new_data2 = new_data1.replace('o', '')
new_data3 = new_data2.replace('e', '')
new_data4 = new_data3.replace('i', '')
print(new_data4)
